version: "3"
services:
  ufire-getway:
    image: ufire-getway
    container_name: ufire-getway
    hostname: ufire-getway
    networks:
      - network
    ports:
      - "9888:9888"
  ufire-websocket-1:
    #docker镜像名称
    image: ufire-websocket
    #docker容器名称
    container_name: ufire-websocket-1
    networks:
      - network
  ufire-websocket-ui:
    #docker镜像名称
    image: ufire-websocket-ui
    #docker容器名称 随机分配IP
    container_name: ufire-websocket-ui
    networks:
      - network
networks:
  network:
    external:
      name: ufire-network
