version: "3"
services:
  ufire-nacos:
    #docker镜像名称
    image: ufire-nacos
    #docker容器名称
    container_name: ufire-nacos
    #指定docker域名(分配随机IP)
    hostname: ufire-nacos
    restart: always
    #指定服务运行的端口 映射8848到宿主机
    ports:
      - "8848:8848"
  ufire-redis:
    #docker镜像名称
    image: redis
      #docker容器名称
    container_name: ufire-redis
      #指定docker域名(分配随机IP)
    hostname: ufire-redis
      #指定服务运行的端口 映射6379到宿主机
    ports:
        - "6379:6379"
  ufire-getway:
    image: ufire-getway
    container_name: ufire-getway
    hostname: ufire-getway

  ufire-websocket-1:
    #docker镜像名称
    image: ufire-websocket
      #docker容器名称
    container_name: ufire-websocket-1
      #指定docker域名(分配随机IP)
  ufire-websocket-2:
    #docker镜像名称
    image: ufire-websocket
      #docker容器名称 随机分配IP
    container_name: ufire-websocket-2
  ufire-websocket-3:
    #docker镜像名称
    image: ufire-websocket
      #docker容器名称 随机分配IP
    container_name: ufire-websocket-3
networks:
  default:
    external:
      #指定自定义网络
      name: ufirenetwork


