spring:
  profiles:
    active: dev  #读取配置文件类型
  rabbitmq:
    addresses:
    username: guest
    password: guest
    virtual-host: /
    datasource:
      url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver