server:
  port: 9876
spring:
  application:
    name: ufire-websocket-ui
  cloud:
    nacos:
      discovery:
        server-addr: ufire-nacos:8848
#local 本地
#app:
#  wssUrl: ws://localhost:9888/ufire-websocket/socket/
#  messageUrl: http://localhost:9888/ufire-websocket/websocket/to/
app:
  wssUrl: ws://websocket.ufiredong.cn/ufire-websocket/socket/
  messageUrl: http://websocket.ufiredong.cn/ufire-websocket/websocket/to/
feign:
  client:
    websocket: ufire-webocket
