server:
  port: 8099
spring:
  application:
    name: ufire-websocket
  datasource:
    url: jdbc:mysql://8.136.110.11:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: 8.136.110.11:5672
    username: guest
    password: guest
    virtual-host: /
mybatis:
  mapper-locations: classpath：com.springcloud.ufire.core.mapper/*.xml